### ISSUE TITLE
After restoring the course "Submitted portfolios: 0"

### ISSUE THREAD

**Issue by setai-support** [synergylearning/moodle-mod_giportfolio#16]
The portfolio plugin is working as expected in different Moodle versions. The only issue is when I make a backup copy of a course that contains portfolios. If I restore the backup in the same Moodle everything works 100% fine. If I restore the backup in a different Moodle (the Moodle version is not an issue) it does not show me the portfolios (Submitted portfolios: 0) even though it shows me the grades of each student correctly for having submitted the portfolio.

![portfolo 1](https://user-images.githubusercontent.com/79369032/108601318-5ab1cd80-7372-11eb-8833-47f9871cd703.jpg)
![portfolio 2](https://user-images.githubusercontent.com/79369032/108601314-5980a080-7372-11eb-8bd3-35abe600e1d9.jpg)

**Comment by davosmith** [comment]
I've just pushed a fix that should allow backup + restore to work.

It may work if you just deploy on the destination site, but you should probably deploy to both and recreate the backup, if at all possible.

**Comment by setai-support** [comment]
Dear Mr. Smith,

I reinstalled the fixed plugin code on the destination site. Now the portfolio plugin is working as expected. When restoring the courses, the submitted portfolios are shown.

Thank you so so so much! Two thumbs up!

**Comment by davosmith** [comment]
Closing issue - thanks for confirming the fix!
