### ISSUE TITLE
Error reading portfolio chapter.

### ISSUE THREAD

**Issue by AndresMorelos** [synergylearning/moodle-mod_giportfolio#5]
Hi!, the plugin is showing to the students and teacher this phrase

**Error reading portfolio chapter.**

**more info about this error.**

What can be do?

**Comment by davosmith** [comment]
Turn on debugging ( https://docs.moodle.org/en/Debugging ) and copy and paste the full error message.

**Comment by AndresMorelos** [comment]
**Debug info:** 
Error code: errorchapter
**Stack trace:**
line 503 of /lib/setuplib.php: moodle_exception thrown
line 84 of /mod/giportfolio/viewcontribute.php: call to print_error()
**Output buffer:** <br /> <b>Notice</b>: date_default_timezone_set(): Timezone ID '-05:00' is invalid in <b>/var/www/vhosts/savio.utbvirtual.edu.co/lib/classes/date.php</b> on line <b>211</b><br /> <br /> <b>Strict Standards</b>: Declaration of format_weekssavio::get_section_dates() should be compatible with format_weeks::get_section_dates($section, $startdate = false) in <b>/var/www/vhosts/savio.utbvirtual.edu.co/course/format/weekssavio/lib.php</b> on line <b>14</b><br /> <br /> <b>Strict Standards</b>: Declaration of theme_saviotheme_core_renderer::user_menu() should be compatible with core_renderer::user_menu($user = NULL, $withlinks = NULL) in <b>/var/www/vhosts/savio.utbvirtual.edu.co/theme/saviotheme/renderers/core_renderer.php</b> on line <b>0</b><br />

**Comment by davosmith** [comment]
It looks like you are trying to view the student entries, but that there are no chapters in the portfolio for them to contribute to.

If you cannot access the link to create a chapter, then look at the address at the top of the page (with the error) and change it from:
.../viewcontribute.php?userid=XX&id=YY
to
.../edit.php?cmid=YY
(where YY is the number after id= in the broken URL).

**Comment by AndresMorelos** [comment]
You're rigth, thanks you for the info.
